# -*- coding: utf-8 -*-
"""fake_engagement_ml_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjOvbXCTreIUXipoWpPMkkBq5wiGJYhO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import IsolationForest

df = pd.read_csv("/content/fake_engagement_dataset.csv")

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
numeric_cols.remove("flag_label")
scaled_df = df.copy()

scaler = StandardScaler()
scaled_df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

features = numeric_cols

X_class = scaled_df[features]
y_class = df["flag_label"]

X_reg = scaled_df[features]
y_reg = df["authenticity_score"]

Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_class, y_class, test_size=0.2, random_state=42
)

Xr_train, Xr_test, yr_train, yr_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

clf = RandomForestClassifier(n_estimators=300, random_state=42)
clf.fit(Xc_train, yc_train)

pred_class = clf.predict(Xc_test)
pred_proba = clf.predict_proba(Xc_test)[:, 1]

reg = RandomForestRegressor(n_estimators=300, random_state=42)
reg.fit(Xr_train, yr_train)

pred_reg = reg.predict(Xr_test)

iso = IsolationForest(contamination=0.10, random_state=42)
df["anomaly_score"] = iso.fit_predict(X_class)
df["anomaly_flag"] = df["anomaly_score"].apply(lambda x: 1 if x == -1 else 0)

print("\nClassification Results")
print("Accuracy :", accuracy_score(yc_test, pred_class))
print("Precision:", precision_score(yc_test, pred_class))
print("Recall   :", recall_score(yc_test, pred_class))
print("F1 Score :", f1_score(yc_test, pred_class))
print("ROC-AUC  :", roc_auc_score(yc_test, pred_proba))

print("\nRegression Results")
print("MAE :", mean_absolute_error(yr_test, pred_reg))
print("RMSE:", np.sqrt(mean_squared_error(yr_test, pred_reg)))
print("R²  :", r2_score(yr_test, pred_reg))

plt.figure(figsize=(12, 6))
sns.heatmap(df[numeric_cols + ["flag_label"]].corr(), cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df["bot_probability"], kde=True)
plt.title("Bot Probability Distribution")
plt.xlabel("Bot Probability")
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df["authenticity_score"], kde=True)
plt.title("Authenticity Score Distribution")
plt.xlabel("Score")
plt.show()

importances = pd.Series(clf.feature_importances_, index=features).sort_values(ascending=False)
plt.figure(figsize=(10, 6))
importances.head(15).plot(kind="barh")
plt.title("Top Feature Importances (Bot Classifier)")
plt.xlabel("Importance")
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(x=df["timing_regularization"], y=df["bot_probability"], hue=df["flag_label"])
plt.title("Timing Regularization vs Bot Probability")
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(x=df["avg_engagement_interval"], y=df["burst_engagement_count"], hue=df["anomaly_flag"])
plt.title("Anomaly Detection — Isolation Forest")
plt.show()

print("Pipeline Completed Successfully")